#!/bin/bash
# Quick Reference for Gradio Animate App
# ========================================

echo "🎭 Wan2.2 Animate Gradio Interface"
echo "===================================="
echo ""
echo "📍 Location: /workspace/wan22-comfy-project/Wan2.2"
echo "🐍 Python: /workspace/wan22-comfy-project/venv/bin/python"
echo "🌐 Port: 7862"
echo ""
echo "Quick Commands:"
echo "---------------"
echo ""
echo "1️⃣  Launch Gradio UI:"
echo "   cd /workspace/wan22-comfy-project/Wan2.2"
echo "   ./launch_animate_ui.sh"
echo ""
echo "2️⃣  Direct Python Launch:"
echo "   /workspace/wan22-comfy-project/venv/bin/python gradio_animate_app.py"
echo ""
echo "3️⃣  Pre-download Models (CLI):"
echo "   /workspace/wan22-comfy-project/venv/bin/python setup_animate_cache.py quick"
echo ""
echo "4️⃣  Run Tests:"
echo "   /workspace/wan22-comfy-project/venv/bin/python test_gradio_animate.py"
echo ""
echo "📁 Example Files:"
echo "   Video: /workspace/wan22-comfy-project/Wan2.2/examples/pose.mp4"
echo "   Image: /workspace/wan22-comfy-project/Wan2.2/examples/pose.png"
echo ""
echo "🔗 Access UI at: http://0.0.0.0:7862"
echo ""
echo "📋 Workflow:"
echo "   1. Setup → Download/Load Models (~50GB first time)"
echo "   2. Preprocess → Upload video + reference image"
echo "   3. Generate → Create animated video"
echo ""
echo "💾 Output Directory: /workspace/wan22-comfy-project/outputs"
echo ""
echo "✅ Status: Integrated cache management complete!"
echo "   - Auto-downloads from: Wan-AI/Wan2.2-Animate-14B"
echo "   - Smart caching enabled"
echo "   - Resume download supported"
echo ""
